# Generated by Django 3.2.12 on 2022-02-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=255)),
                ('apellido_alumno', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_prof', models.CharField(max_length=255)),
                ('apellido_prof', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_prueba', models.SmallIntegerField()),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('codigo_curso', models.ForeignKey(db_column='codigo_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='tablas.cursos')),
                ('rut_alumno', models.ForeignKey(db_column='rut_alumno', on_delete=django.db.models.deletion.DO_NOTHING, to='tablas.alumnos')),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='rut_prof_asig',
            field=models.ForeignKey(db_column='rut_prof_asig', on_delete=django.db.models.deletion.DO_NOTHING, to='tablas.profesores'),
        ),
    ]
